#!/bin/sh

pip3 install --no-deps .
install -Dm644 icons/64x64.png   /usr/share/icons/hicolor/64x64/apps/io.github.jordanl2.ModularCalculator.png
install -Dm644 icons/128x128.png /usr/share/icons/hicolor/128x128/apps/io.github.jordanl2.ModularCalculator.png
install -Dm644 icons/256x256.png /usr/share/icons/hicolor/256x256/apps/io.github.jordanl2.ModularCalculator.png
install -D ModularCalculator.desktop /usr/share/applications/io.github.jordanl2.ModularCalculator.desktop
install -D io.github.jordanl2.ModularCalculator.appdata.xml /usr/share/metainfo/io.github.jordanl2.ModularCalculator.metainfo.xml
