#!/bin/sh

PREFIX=$1
if [ $# -lt 1 ]; then
	PREFIX=/usr
fi

pip3 uninstall modularcalculator -y
for r in 64x64 128x128 256x256
do
	rm $PREFIX/share/icons/hicolor/$r/apps/io.github.jordanl2.ModularCalculator.png
done
rm $PREFIX/share/applications/io.github.jordanl2.ModularCalculator.desktop
rm $PREFIX/share/metainfo/io.github.jordanl2.ModularCalculator.metainfo.xml
