#!/bin/sh

cd "$(dirname "$0/..")"
./tests/testbasiccalculator.py
./tests/testadvancedcalculator.py
./tests/testscientificcalculator.py
./tests/testcomputingcalculator.py
./tests/testsyntaxerrorhandling.py
